"""governance: organizations, org_memberships, users.is_superuser

Revision ID: 185e089a4a4b
Revises:
Create Date: 2026-09-27 18:03:35.935901

Hand-written baseline governance migration.

This intentionally does ONLY three things:
  1. create `organizations`
  2. create `org_memberships`
  3. add `users.is_superuser` (with a server default so existing rows backfill)

The autogenerated draft also proposed dropping several indexes
(idx_player_name, idx_tournament_date, etc.) and altering TIMESTAMP columns to
DateTime. Those are false diffs: the live schema was built from
database/create_tables.sql, which declares indexes/types the SQLAlchemy models
don't. Applying them would drop useful indexes and cosmetically churn column
types. They are deliberately omitted.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185e089a4a4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'organizations',
        sa.Column('org_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('slug', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('org_id'),
        sa.UniqueConstraint('slug', name='uq_organizations_slug'),
    )

    op.create_table(
        'org_memberships',
        sa.Column('membership_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('org_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'app',
            sa.Enum('dubs', 'tags', 'putt', '*', name='org_app_enum'),
            nullable=False,
            server_default='*',
        ),
        sa.Column(
            'role',
            sa.Enum('admin', 'director', 'viewer', name='org_role_enum'),
            nullable=False,
            server_default='viewer',
        ),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('membership_id'),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.UniqueConstraint('org_id', 'user_id', 'app', name='uq_org_user_app'),
    )

    # Add is_superuser with a server default so existing user rows backfill to
    # false without a NULL violation.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_superuser', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # Seed the Phase 1 default organization (SVDGC). Downstream migrations
    # reference org_id=1 for backfills and FKs.
    conn = op.get_bind()
    existing = conn.execute(
        sa.text("SELECT COUNT(*) FROM organizations WHERE org_id = 1")
    ).scalar()
    if not existing:
        conn.execute(sa.text(
            "INSERT INTO organizations (org_id, slug, name, is_active, created_at) "
            "VALUES (1, 'svdgc', 'Silicon Valley Disc Golf Club', 1, NOW())"
        ))


def downgrade():
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM organizations WHERE org_id = 1"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_superuser')

    op.drop_table('org_memberships')
    op.drop_table('organizations')
